name: Build and Save Docker Image

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build Image
        run: docker build -t mi-sitio-en-docker .

      - name: Archive Image
        run: docker save -o MiSitioEnDocker.tar mi-sitio-en-docker

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Mi-Sitio-En-Docker
          path: MiSitioEnDocker.tar
